name: Run Daily Math Posting
name: Run Daily Math Postings

on:
  schedule:
    # 08:05 AM UTC turns into 10:05 AM in Zurich.
    # Moving it to 5 minutes past the hour cuts through the GitHub traffic jam
    - cron: '5 8 * * *'
    
    # 07:05 PM UTC turns into 09:05 PM (21:05) in Zurich.
    - cron: '5 19 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests gdown

      - name: Run Morning Post
        if: github.event.schedule == '5 8 * * *' || github.event_name == 'workflow_dispatch'
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python bot.py morning

      - name: Run Evening Post
        if: github.event.schedule == '5 19 * * *'
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python bot.py evening
